# Generated by Django 3.1 on 2021-03-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code_for_password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
