# Generated by Django 3.1 on 2021-03-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210314_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='author',
        ),
    ]
