# Generated by Django 3.1 on 2021-03-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210314_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='favourite',
            field=models.BooleanField(default=True),
        ),
    ]
